name: Publish Module

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a multi-line script
      run: Get-ChildItem
      shell: pwsh
    - name: Display the path
      run: build.ps1 -Tasks 'analyze'
      shell: pwsh
